import {chromium} from '@playwright/test';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
await page.goto('http://127.0.0.1:5173/?zone=กรุงเทพใต้&rank=bottom&metric=transit_station_count');
await page.locator('.rank-row').first().waitFor();
await page.locator('.map[data-rendered-districts="50"]').waitFor();
await page.screenshot({path:'../docs/screenshots/zone-ranking.png',fullPage:true});
await page.goto('http://127.0.0.1:5173/district/1007?layer=healthcare');
await page.locator('.pyramid-row').first().waitFor();
await page.locator('.benchmark-badge').first().waitFor();
await page.locator('.pyramid-panel').screenshot({path:'../docs/screenshots/population-pyramid.png'});
await page.locator('.point-list button').first().click();
await page.locator('.maplibregl-popup-content').waitFor();
await page.waitForTimeout(650);
await page.locator('.map-shell').screenshot({path:'../docs/screenshots/poi-focus.png'});
await page.setViewportSize({width:390,height:844});
await page.locator('.pyramid-panel').evaluate(el=>el.scrollIntoView({block:'start'}));
await page.screenshot({path:'../docs/screenshots/population-pyramid-mobile.png'});
await browser.close();
