import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
await fs.mkdir('../docs/screenshots',{recursive:true});
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('heading',{name:'มองกรุงเทพฯ ผ่านข้อมูล'}).waitFor();
await page.locator('.maplibregl-canvas').waitFor();
await page.locator('.map[data-rendered-districts="50"]').waitFor();
await page.screenshot({path:'../docs/screenshots/overview.png',fullPage:true});
await page.goto('http://127.0.0.1:5173/compare?districts=1007,1030');
await page.locator('.comparison-grid').waitFor();
await page.screenshot({path:'../docs/screenshots/compare.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('heading',{name:'มองกรุงเทพฯ ผ่านข้อมูล'}).waitFor();
await page.locator('.map[data-rendered-districts="50"]').waitFor();
await page.screenshot({path:'../docs/screenshots/mobile.png',fullPage:true});
console.log('Screenshots saved');await browser.close();
